import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#f7fbf0',
        'surface-dim': '#d7dbd2',
        'surface-bright': '#f7fbf0',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f5eb',
        'surface-container': '#ebefe5',
        'surface-container-high': '#e5eadf',
        'surface-container-highest': '#e0e4da',
        'on-surface': '#181d17',
        'on-surface-variant': '#40493d',
        'inverse-surface': '#2d322b',
        'inverse-on-surface': '#eef2e8',
        'outline': '#707a6c',
        'outline-variant': '#bfcaba',
        'surface-tint': '#1b6d24',
        'primary': '#0d631b',
        'on-primary': '#ffffff',
        'primary-container': '#2e7d32',
        'on-primary-container': '#cbffc2',
        'inverse-primary': '#88d982',
        'secondary': '#286b33',
        'on-secondary': '#ffffff',
        'secondary-container': '#abf4ac',
        'on-secondary-container': '#2e7238',
        'tertiary': '#923357',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#b14b6f',
        'on-tertiary-container': '#ffedf0',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#a3f69c',
        'primary-fixed-dim': '#88d982',
        'on-primary-fixed': '#002204',
        'on-primary-fixed-variant': '#005312',
        'secondary-fixed': '#abf4ac',
        'secondary-fixed-dim': '#90d792',
        'on-secondary-fixed': '#002107',
        'on-secondary-fixed-variant': '#07521d',
        'tertiary-fixed': '#ffd9e2',
        'tertiary-fixed-dim': '#ffb1c7',
        'on-tertiary-fixed': '#3f001c',
        'on-tertiary-fixed-variant': '#7f2448',
        'background': '#f7fbf0',
        'on-background': '#181d17',
        'surface-variant': '#e0e4da',
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'xxl': '48px',
        'container-margin': '24px',
        'gutter': '16px',
        'unit': '8px',
      },
      fontFamily: {
        poppins: ['Poppins', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        'display-lg': ['Poppins', 'sans-serif'],
        'headline-lg': ['Poppins', 'sans-serif'],
        'headline-md': ['Poppins', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};

export default config;
